### PR TITLE
update(docs): update Linux quickstart tutorial to work with Ubuntu 24.04

### PR DESCRIPTION
**Pull request by ekoops**
**What type of PR is this?**

/kind content

**Any specific area of the project related to this PR?**

/area documentation

**What this PR does / why we need it**:

This PR updates the Linux quickstart tutorial to work with Ubuntu 24.04 virtual machines. Moreover, it corrects some version discrepancies throughout the document. 

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by LucaGuerra** [comment]
There is a section related to installing kernel headers. This shouldn't be necessary on Ubuntu 24.04 I think, since it uses the modern_ebpf probe. Could you please check? 🙏

**Comment by leogr** [comment]
FYI - testing on Apple Silicon rn

**Review by leogr — CHANGES_REQUESTED** [review]
Since we now are using the modern, below other required changes:
- Just `sudo apt-get install -y dialog` (no need to install kernel and other stuff)
- In the dialog, invite the user to select `Modern eBPF` instead of `Automatic Selection` 
- `systemctl status falco-modern-bpf.service`

Otherwise, LGTM.

Moreover, I've tried it on Apple Silicon, and it worked fine!

Thank you!
-

**Comment by ekoops** [comment]
I included the requested changes. Thank you!

**Review by leogr — APPROVED** [review]
Great, thank you!

**Pull request merged**
