### PR TITLE
vote: update(OWNERS): add myself as an approver

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

**Any specific area of the project related to this PR?**

**What this PR does / why we need it**:

As mentioned in the community call on Oct 25th I would like to help with the website repo maintenance

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by leogr** [comment]
+1 from me

**Comment by jasondellaluce** [comment]
+1

**Comment by vjjmiras** [comment]
+1

**Comment by Issif** [comment]
+1

**Review by leogr — APPROVED** [review]
:partying_face:

**Pull request merged**
