### PR TITLE
Translate docs/installation page into Korean

### LINKED ISSUE #275: Translate docs/installation into Korean
/area documentation
/kind content
/kind translation

**What would you like to be added:**
Translate docs/installation into Korean

**Why is this needed:**
No ko doc for docs/installation

### PR DESCRIPTION
**Pull request by futureCreator**
**What type of PR is this?**
/kind content
/kind translation

**Any specific area of the project related to this PR?**
/area documentation

**What this PR does / why we need it**:
Translate Installation page(`/docs/installation`) to Korean.

**Which issue(s) this PR fixes**:
Fixes #275 

**Special notes for your reviewer**:
@jmyung

### CODE REVIEW

**Comment by futureCreator** [comment]
Preview page
👉 https://deploy-preview-280--falcosecurity.netlify.app/ko/docs/installation/

**Review by leodido — APPROVED** [review]
🇰🇷  thanks!

**Comment by futureCreator** [comment]
Thanks for approving! 🎉

**Pull request merged**
