### PR TITLE
update: make toc follow the scroll

### PR DESCRIPTION
**Pull request by fntlnz**
Signed-off-by: Lorenzo Fontana <lo@linux.com>

**What type of PR is this?**
I was very annoyed by having to scroll up to find subsections in [the build page](https://falco.org/docs/source/) so I made some CSS (I'm very bad at that, please review)!

/kind user-interface

**Any specific area of the project related to this PR?**

**What this PR does / why we need it**:
We want to find sections easily!

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by fntlnz** [comment]
Before
2020-01-22_3360x1194_scrot
After
2020-01-22_3370x1253_scrot

**Comment by leodido** [comment]
Screenshot 2020-01-22 at 12 44 41

**Comment by lucperkins** [comment]
I'm not a web designer but in general `position: fixed` is a recipe for opposite-of-fun. I can make a stab at this.

**Comment by fntlnz** [comment]
I'm not a webdesigner at all too @lucperkins ! Thanks for getting that done, closing this in favor of #118 

/close

**Pull request closed without merging**
