### PR TITLE
Added contribution guidelines 

### PR DESCRIPTION
**Pull request by Rajakavitha1**
Signed-off-by: Rajakavitha Kodhandapani <krajakavitha@gmail.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

/kind cleanup

> /kind design

> /kind user-interface

> /kind content

> /kind translation

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area blog

> /area documentation

> /area videos

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
Fixed the broken link to guidelines in https://falco.org/community/

Here's the preview of the page that has the link fixed:https://deploy-preview-367--falcosecurity.netlify.app/community/

### CODE REVIEW

**Review by leodido — COMMENTED** [review]
Can we please include the markdown document with a Hugo shortcode?

That way we don't need to keep this in sync and use .github/CONTRIBUTING.md as the only source of truth (that simply is reported on the website too).

/hold

**Comment by Rajakavitha1** [comment]
> Can we please include the markdown document with a Hugo shortcode?
> 
> That way we don't need to keep this in sync and use .github/CONTRIBUTING.md as the only source of truth (that simply is reported on the website too).
> 
> /hold

This, is just a stop gap fix. We need contributor guidelines for the documentation/website and contributor guidelines for developers. For now we don't have one for the documentation similar to : https://kubernetes.io/docs/contribute/ and when we have falcosecurity.dev website we need something similar to https://www.kubernetes.dev/docs/

**Comment by Rajakavitha1** [comment]
@leodido added the link to the .md file on GitHub :)

**Review by leogr — APPROVED** [review]
As discussed with @leodido and @fntlnz, using a simple link is a good tradeoff (rather than a short code that would fetch a build time).

So, ok for me!

**Pull request merged**
