### PR TITLE
Add docs for exceptions support

### PR DESCRIPTION
**Pull request by mstemm**
Add docs that note the new exceptions fields and a standalone page that
describes how exceptions work in more detail. Text borrowed heavily from
the original exceptions proposal.

Signed-off-by: Mark Stemm <mark.stemm@gmail.com>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind user-interface

/kind content

> /kind translation

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area blog

/area documentation

> /area videos

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by leogr** [comment]
Thank you, Mark!

I'm just putting this PR on hold since we have to release Falco 0.27.0 first.
/hold

**Review by leogr — APPROVED** [review]

**Review by leodido — APPROVED** [review]

**Comment by Rajakavitha1** [comment]
Hi @leogr Now that the website has been released can you please remove the hold?

**Comment by leogr** [comment]
> Hi @leogr Now that the website has been released can you please remove the hold?

I've a doubt. This feature is not present in 0.27.0, but it has been merged on master and will be released within 0.28.0.
Shall we include it in the documentation now?

@Rajakavitha1 @leodido @fntlnz WDYT?

**Comment by Rajakavitha1** [comment]
> > Hi @leogr Now that the website has been released can you please remove the hold?
> 
> I've a doubt. This feature is not present in 0.27.0, but it has been merged on master and will be released within 0.28.0 (see [falcosecurity/falco#1427](https://github.com/falcosecurity/falco/pull/1427)).
> Shall we include it in the documentation now?
> 
> @Rajakavitha1 @leodido @fntlnz WDYT?

May be we should wait until the release of 0.28.0. We don't want to publish about any feature that is not released yet.

**Comment by leodido** [comment]
Well, the feature is already present in Falco 0.27.0-x versions (those being released automatically from the merges on the master branch).

Precisely this feature is available starting with Falco [0.27.0-15+8c4040b](https://bintray.com/falcosecurity/deb-dev/falco/0.27.0-15%2B8c4040b).

The current website is about v0.27.0 version. But I would include also the feature coming with all the 0.27.0-x version since we have a 2-month release cadence.

What I suggest to do is to put a disclaimer/warning box (we have CSS classes to do it) clarifying that such feature is present in the _development versions of Falco_ (ie.,  0.27.0-x).

**Pull request merged**
