### PR TITLE
Typo correction

### LINKED ISSUE #299: Typo correction in docs/installation
**What is wrong with the website or needs to be cleaned?**
Correct typos `into into` 👉 `into` in `docs/installation` page.

### PR DESCRIPTION
**Pull request by futureCreator**
**What type of PR is this?**
/kind cleanup

**Any specific area of the project related to this PR?**
/area documentation

**What this PR does / why we need it**:
Correct typos 'into into' 👉 'into' in `docs/installation` page.

**Which issue(s) this PR fixes**:
Fixes #299 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by futureCreator** [comment]
Preview page 👇 
https://deploy-preview-300--falcosecurity.netlify.app/docs/installation/

**Review by leogr — APPROVED** [review]
Good catch :+1:

**Comment by futureCreator** [comment]
Thanks for approving! 🙏

**Comment by leogr** [comment]
You are welcome!

**Pull request merged**
