### PR TITLE
Display the CRI options to use when using K3S

### PR DESCRIPTION
**Pull request by patrickdung**
Let users know about the CRI options (provided by @pabloopez) to use when using K3S 
Original discussion is in here https://github.com/falcosecurity/falco/issues/1911

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind user-interface

/kind content

> /kind translation

**Any specific area of the project related to this PR?**
Documentation

> Uncomment one (or more) `/area <>` lines:

> /area blog

/area documentation

> /area videos

**What this PR does / why we need it**:
Let users know what parameters should be configured for CRI when using K3S.
The default setting used in Falco does not match the one used in K3S.

**Which issue(s) this PR fixes**:

https://github.com/falcosecurity/falco/issues/1911

Fixes https://github.com/falcosecurity/falco/issues/1911

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by pabloopez** [comment]
Thanks for starting the discussion @patrickdung !

I like the idea of including it here instead of the install section. But at the same time I believe that there might be people trying to run Falco on a single host where docker is not present and it is required to specify an option with the path to the container runtime. 

Let's see what others here in the community think about this. I believe it is useful to include this information in the docs but I am not sure about where should we do it.

**Comment by patrickdung** [comment]
Yes, when I looked at the "Deployment section", the content is actually meaning Deployment with Kubernetes...

Maybe we should put another a note about the CRI option when Falco is install on host in in the install section?

**Comment by pabloopez** [comment]
> Yes, when I looked at the "Deployment section", the content is actually meaning Deployment with Kubernetes...
> 
> Maybe we should put another a note about the CRI option when Falco is install on host in in the install section?

I believe it is a good idea, let's see what some of the mainteiners here think about it.

@Issif what are your thoughs about this?

**Comment by Issif** [comment]
To keep consistency with other k8s distros, I think it should be added in this section of docs https://falco.org/docs/getting-started/third-party/learning/

**Comment by patrickdung** [comment]
@lssif
That section should be for learning environment (minikube/kind/microk8s). IMHO K3S is more inclined to be used for production environment.

Maybe update the information in [this section](https://falco.org/docs/getting-started/third-party/production/)?

**Comment by Issif** [comment]
I mostly used K3s for locale tests than for Production purpose but I get your point, to be honest, I think we should not split this and have only 1 page with all k8s solutions. Ok for me to add it in production page anyway.

cc @radhikapc @Rajakavitha1

**Comment by patrickdung** [comment]
@Issif
cc @radhikapc @Rajakavitha1

What I meant is K3S is a production Kubernetes distribution. But I am not sure if Falco + K3S is a production setting or not.

**Review by leogr — APPROVED** [review]

**Review by leogr — CHANGES_REQUESTED** [review]
I like the idea of including this in the documentation. However, I agree @pabloopez that the "deployment" section is not the right place.

I also think we can't assume K3s as a learning environment only, so if there's no better place, this content should be moved to https://falco.org/docs/getting-started/third-party/production/

Please consider expanding it a bit and adding more detail about the Falco installation in K3s, if any.

**Comment by leogr** [comment]
> Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.
> 
> memo **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falco-website/blob/master/CONTRIBUTING.md) to update your commits with the DCO**
> 
> Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).
> 
> **The list of commits missing DCO signoff**:
> 
> * [b75d245](https://github.com/falcosecurity/falco-website/commits/b75d245a763115375aed8ac3cd88ef060c6d4ff9) Merge branch 'master' into patch-1
> * [c969acb](https://github.com/falcosecurity/falco-website/commits/c969acb332a4645cfc047b9819152c809af756cc) revert the change to deployment.md (not adding the content to deployment.md)

Hey @patrickdung 

Merge commits are not allowed, could you rebase pls? :pray: 
Also, make sure all commits are signed-off

**Comment by patrickdung** [comment]
> > Thanks for your pull request. Before we can look at it, you'll need to add a 'DCO signoff' to your commits.
> > memo **Please follow instructions in the [contributing guide](https://github.com/falcosecurity/falco-website/blob/master/CONTRIBUTING.md) to update your commits with the DCO**
> > Full details of the Developer Certificate of Origin can be found at [developercertificate.org](https://developercertificate.org/).
> > **The list of commits missing DCO signoff**:
> > 
> > * [b75d245](https://github.com/falcosecurity/falco-website/commits/b75d245a763115375aed8ac3cd88ef060c6d4ff9) Merge branch 'master' into patch-1
> > * [c969acb](https://github.com/falcosecurity/falco-website/commits/c969acb332a4645cfc047b9819152c809af756cc) revert the change to deployment.md (not adding the content to deployment.md)
> 
> Hey @patrickdung
> 
> Merge commits are not allowed, could you rebase pls? 🙏 Also, make sure all commits are signed-off

@leogr Thanks for reminding. Rebase is new to me. Let me check and test. I will let you know when it is ready to check the PR.

**Comment by patrickdung** [comment]
I will create another PR, please ignore this PR.

**Pull request closed without merging**
