### PR TITLE
update(config.toml): archive v0.32

### LINKED ISSUE #796: Translate grpc/grpc-config in Korean
/area documentation

**What would you like to be added**:

**Why is this needed**:
No translation with grpc/grpc-config in Korean

**Comments**
The security of Kubernetes in the cloud is essential.
Not only English, but also various language support is needed.
So, Falco Doc's technical documentation needs Korean.

Page to Update:
https://falco.org/docs/grpc/grpc-config/

### PR DESCRIPTION
**Pull request by Virusuki**
**What type of PR is this?**

> /kind translation

**Any specific area of the project related to this PR?**

> /area documentation

**What this PR does / why we need it**:
No translation with grpc/grpc-config in Korean

**Which issue(s) this PR fixes**:

Fixes #796

**Special notes for your reviewer**:

### CODE REVIEW

**Review by jasondellaluce — CHANGES_REQUESTED** [review]
It's not clear to me how this fixes https://github.com/falcosecurity/falco-website/issues/796, and the commit you pushed has my sign-off.

Please remove my sign-off as these are not changes I authored, and give further context on how this fixes the issue you linked.

**Review by vjjmiras — CHANGES_REQUESTED** [review]
This PR looks like a mistake to me, since it includes an older commit submitted by a different contributor and nothing else.
Can you clarify what the intention of the PR is?

**Comment by Virusuki** [comment]
Sorry. it's a PR mistake.

I'll leave a comment on the https://github.com/falcosecurity/falco-website/issues/796 issue.

**Comment by vjjmiras** [comment]
Thank you for taking care of it, @Virusuki.

**Pull request closed without merging**
