### PR TITLE
rename and join posts as a serie for kubernetes response engine

### PR DESCRIPTION
**Pull request by Issif**
Signed-off-by: Issif <issif_github@gadz.org>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind user-interface

/kind content

> /kind translation

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area blog

> /area documentation

> /area videos

**What this PR does / why we need it**:

Rename and join blog posts about kubernetes response engine as a serie

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by developer-guy** [comment]
looks good @Issif 👍

**Review by leogr — COMMENTED** [review]
LGTM, but before approving I have a question:

Are we sure we want to change the slugs? That would break any link pointing to the current blog's URLs.

Let me know!

**Comment by Issif** [comment]
> LGTM, but before approving I have a question:
> 
> Are we sure we want to change the slugs? That would break any link pointing to the current blog's URLs.
> 
> Let me know!

I wondered myself, I know it breaks SEO and links, but my guess was it's cleaner to have same patterns for all blogs posts URL. As you will.

**Comment by leogr** [comment]
> As you will.

No problem for me, I just wanted to be sure. I'm approving :+1:

**Review by leogr — APPROVED** [review]

**Pull request merged**
