### PR TITLE
docs:falco-0-28-0.md file translation Chinese

### PR DESCRIPTION
**Pull request by cytianying**
docs:falco-0-28-0.md file translation Chinese

Signed-off-by: tianying tianying@uniontech.com

### CODE REVIEW

**Comment by vjjmiras** [comment]
Review in progress
/hold

**Review by frankspeak32 — CHANGES_REQUESTED** [review]

**Comment by vjjmiras** [comment]
@cytianying Could you review the suggestions?

**Comment by cytianying** [comment]
> 
Ok, I'll modify it. Thank you

**Pull request closed without merging**
