### PR TITLE
fix: update broken links in README.md

### LINKED ISSUE #361: README.md contains 4 broken links to config.yaml
**What is wrong with the website or needs to be cleaned?**

There are broken links in README.md.
The link target might be `config.toml` instead of `config.yaml`.

### PR DESCRIPTION
**Pull request by oke-py**
Signed-off-by: Naoki Oketani <okepy.naoki@gmail.com>

**What type of PR is this?**

/kind cleanup

**Any specific area of the project related to this PR?**

/area documentation

**What this PR does / why we need it**:

README.md contains 4 broken links to config.yaml.

**Which issue(s) this PR fixes**:

Fixes #361 

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by Rajakavitha1** [comment]
Thank you @oke-py !!!
/lgtm

**Review by leogr — APPROVED** [review]
good catch! Thanks!

**Pull request merged**
