### PR TITLE
wip: fix(content/ml/about): remove symlink

### PR DESCRIPTION
**Pull request by leogr**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind bug

/kind cleanup

> /kind design

> /kind user-interface

> /kind content

> /kind translation

> /kind event

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area blog

> /area documentation

> /area community

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by LucaGuerra — COMMENTED** [review]
This is exactly what we needed.

**Comment by LucaGuerra** [comment]
Actually I tested this and we can open a PR with all of them.

**Comment by vjjmiras** [comment]
@LucaGuerra, I get the following error when I try to open `About` after having selected the Malayalam language:
NotFound

**Comment by leogr** [comment]
Closing in favor of https://github.com/falcosecurity/falco-website/pull/1154
/close

**Pull request closed without merging**
