### PR TITLE
docs: ubuntu 18.04 specific instructions

### PR DESCRIPTION
**Pull request by fntlnz**
Signed-off-by: Lorenzo Fontana <fontanalorenz@gmail.com>

**What type of PR is this?**

/kind content

**Any specific area of the project related to this PR?**

/area documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by fntlnz** [comment]
/hold

This can only be merged after: https://github.com/falcosecurity/falco/pull/1353

**Review by leodido — APPROVED** [review]

**Review by leogr — APPROVED** [review]
:+1:

**Review by leogr — APPROVED** [review]
LGTM

**Pull request merged**
