### PR TITLE
Add link checker

### PR DESCRIPTION
**Pull request by lucperkins**
This PR adds a link checker to the website's CI pipeline and fixes existing broken links.

### CODE REVIEW

**Comment by fntlnz** [comment]
Good job! Thanks @lucperkins

**Comment by leodido** [comment]
LGTM @lucperkins!

Needs a rebase on top of master, btw :)

**Comment by fntlnz** [comment]
/hold

This pr has conflicts and is in merge pool so its blocking other PRs.

**Comment by fntlnz** [comment]
Anyone please remove the hold once a rebase is done, it seems that there are conflicts

**Pull request merged**
