### PR TITLE
Videos on the Falco website and layout improvements

### PR DESCRIPTION
**Pull request by fntlnz**
**What type of PR is this?**

As discussed in the last community call [here](https://github.com/falcosecurity/community/blob/master/meeting-notes/2020-09-16.md#this-week-highlights) I'm following up with some improvements to the Falco website, namely:

- Videos can be updated using `config.yaml`
- Featured video in the home page is the most recent one in `config.yaml`
- Each language has its own video list
- Bonus: CSS fixes

*Screenshots*

Featured video in home page:

image

Video list: 

image

**Any specific area of the project related to this PR?**

/area documentation

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by fntlnz** [comment]
Also if Luc has time to review this

/cc @lucperkins

**Review by leodido — DISMISSED** [review]
CSS 🌠  + Videos 🎥  = LGTM 🚀

**Comment by fntlnz** [comment]
Also I did some translation for this in the zh and jp languages. PTAL @TakaoShimizu and @Kaizhe

**Review by leodido — APPROVED** [review]
CSS 🌠 + Videos 🎥 = LGTM 🚀

**Review by leogr — APPROVED** [review]

**Pull request merged**
