### PR TITLE
Add basic blog template

### PR DESCRIPTION
**Pull request by lucperkins**

### CODE REVIEW

**Comment by Issif** [comment]
You mean an `archetype` in hugo "language"?

**Comment by lucperkins** [comment]
@Issif No, this is not a Hugo archetype. This is a set of HTML templates.

**Comment by fntlnz** [comment]
This looks very good! Thanks Luc!
My only thing is that I think we want to remove the page date from the blog post list.

It was intentional?

2019-08-30_1203x533_scrot

**Comment by lucperkins** [comment]
@leodido @fntlnz Honestly, I don't think I've ever seen a blog that *doesn't* display the publish date of posts. I can remove it from the post list on `/blog` but I think it's important to retain it in the posts themselves.

**Comment by lucperkins** [comment]
@leodido @fntlnz Oh wait, I see what you mean now. Weird. I actually don't know why it's doing that but I'll fix.

**Pull request merged**
