### PR TITLE
wip: update(content): update running docs for Falco 0.34.

### PR DESCRIPTION
**Pull request by FedeDP**
**What type of PR is this?**

/kind cleanup
/kind content

**Any specific area of the project related to this PR?**

/area documentation

**What this PR does / why we need it**:

Falco 0.34 changed the way we manage our deb/rpm systemd units: https://github.com/falcosecurity/falco/pull/2242.
Update doc accordingly.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by FedeDP** [comment]
Keep this on hold until Falco 0.34.
/hold

**Comment by Andreagit97** [comment]
Closed in favor of https://github.com/falcosecurity/falco-website/pull/799

**Comment by FedeDP** [comment]
/close
Thank you Andrea!

**Pull request closed without merging**
