### PR TITLE
new(blog): Small how-to for Falco on M1 via Lima

### PR DESCRIPTION
**Pull request by e-minguez**
**What type of PR is this?**

/kind content

**Any specific area of the project related to this PR?**

/area blog

**What this PR does / why we need it**:

It adds a new article to the Falco blog on how to install Falco on Apple Silicon via Lima

**Which issue(s) this PR fixes**:

None

Fixes #

None

**Special notes for your reviewer**:

I was wondering if including how to install Falco on K8s on M1, but I don't know if the article length would be too much. Thoughts?

### CODE REVIEW

**Comment by Issif** [comment]
Really cool, thank you. We've a post ready for today, I saw the date is 20th of September for yours, it's perfect. Let me approve when it's the right time.

**Comment by e-minguez** [comment]
> Really cool, thank you. We've a post ready for today, I saw the date is 20th of September for yours, it's perfect. Let me approve when it's the right time.

I choose the date randomly, to be honest 😅 
I've force-pushed an updated version including how to deploy it on K8s as well. WDYT?
Thanks!

**Comment by e-minguez** [comment]
I've just force-pushed a version with fewer grammar errors, the content is the same :)

**Comment by e-minguez** [comment]
pinging @Issif for review/approval :) Thanks!!

**Review by Issif — APPROVED** [review]

**Pull request merged**
