### PR TITLE
cleanup(metrics): update example outputs for falco 0.38.0

### PR DESCRIPTION
**Pull request by incertum**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind user-interface

/kind content

> /kind event

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area blog

/area documentation

> /area community

**What this PR does / why we need it**:

Update example metrics outputs for Falco 0.38.0.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by incertum** [comment]
/hold

until 0.38.0 release

Merge https://github.com/falcosecurity/falco-website/pull/1318 first, then rebase and merge this one.

/milestone falco-0.38.0

**Comment by incertum** [comment]
CC @sgaist

**Review by sgaist — APPROVED** [review]

**Review by LucaGuerra — DISMISSED** [review]

**Comment by LucaGuerra** [comment]
Hey @incertum , I think you just need to rebase this one! 😅

**Comment by incertum** [comment]
Done @LucaGuerra :)

**Review by LucaGuerra — APPROVED** [review]

**Pull request merged**
