### PR TITLE
blog: typo fix in intro-k8s-security-monitoring blog

### PR DESCRIPTION
**Pull request by freddyfernando**
**What type of PR is this?**

/kind content

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area blog

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:
Edit: typo fix in intro-k8s-security-monitoring blog

### CODE REVIEW

**Comment by freddyfernando** [comment]
Can't seem to access https://github.com/falcosecurity/falco-website/blob/master/CONTRIBUTING.md
What do I have to add for dco-signoff?

**Comment by leogr** [comment]
> Can't seem to access https://github.com/falcosecurity/falco-website/blob/master/CONTRIBUTING.md
> What do I have to add for dco-signoff?

Hi,

I apologize for the link; it's broken. The correct one is https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md#developer-certificate-of-origin

To signoff a commit, you should add the `-s` option to your git commit command.

Also, I have noticed that this PR includes a [merge commit](https://github.com/falcosecurity/falco-website/pull/351/commits/c99ade1d7937a9153ba52ffa29ef06a7b7d70940). Merge commits are not allowed on our repositories, so I'd advise you to sync (or recreate) your fork from the current master branch.

**Comment by freddyfernando** [comment]
Alright, thanks.

**Comment by freddyfernando** [comment]
I've created another PR for this. We can close this one if possible.

**Comment by leogr** [comment]
> I've created another PR for this. We can close this one if possible.
:+1: 

btw, I can't find the other PR, anyway we can close this whenever you prefer.

**Pull request closed without merging**
