### PR TITLE
fix(content/en/docs/install-operate/installation.md): fix broken link

### PR DESCRIPTION
**Pull request by maxgio92**
**What type of PR is this?**

/kind bug

**Any specific area of the project related to this PR?**

/area documentation

**What this PR does / why we need it**:

This PR fixes a broken link in the troubleshooting documentation, to a tutorial page.

**Which issue(s) this PR fixes**:

NA

**Special notes for your reviewer**:

NA

### CODE REVIEW

**Comment by maxgio92** [comment]
PTAL @vjjmiras
My bad

**Review by vjjmiras — DISMISSED** [review]
LGTM

**Review by vjjmiras — APPROVED** [review]
LGTM

**Pull request merged**
