### PR TITLE
new(docs): add rule selection documentation

### LINKED ISSUE #1316: Add documentation for rule selection configuration
/area documentation

**What would you like to be added**:

See https://github.com/falcosecurity/falco/pull/3178 implementation and discussion

**Why is this needed**:

### PR DESCRIPTION
**Pull request by LucaGuerra**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

/kind content

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

/area documentation

**What this PR does / why we need it**:

Document this: https://github.com/falcosecurity/falco/pull/3178

**Which issue(s) this PR fixes**:

Fixes #1316

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by LucaGuerra** [comment]
/hold

until 0.38.0 release

**Comment by incertum** [comment]
Nice!

If we accept the patch that prints all enabled rules when running Falco with `-o log_level=debug` similar to how we print the final set of syscalls please add that to the docs.

In addition, would say it's worth another announcement update in the rules repo readme https://github.com/falcosecurity/rules.

**Review by leogr — APPROVED** [review]

**Pull request merged**
