### PR TITLE
docs_fix(little typo)

### PR DESCRIPTION
**Pull request by pabloopez**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind user-interface

/kind content

> /kind translation

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area blog

/area documentation

> /area videos

**What this PR does / why we need it**:
just a little typo

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Review by Issif — APPROVED** [review]
Thanks.

**Comment by Issif** [comment]
@pabloopez you forgot to sign-off your commit, can you run these commands, please:
```shell+
git commit --amend -s
git push origin patch-1 -f
```

**Review by leogr — APPROVED** [review]
Thank you!

**Pull request merged**
