### PR TITLE
update(docs): use the correct helm options based on v2.0.0 of the faco chart

### PR DESCRIPTION
**Pull request by alacuku**
Signed-off-by: Aldo Lacuku <aldo@lacuku.eu>

**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind user-interface

> /kind content

> /kind translation

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area blog

/area documentation

> /area videos

**What this PR does / why we need it**:

Update some outdated helm commands.

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by alacuku** [comment]
@vjjmiras @jasondellaluce

**Comment by jasondellaluce** [comment]
@alacuku LGTM, should this wait for Falco 0.33 to be released or can we merge this before?

**Comment by alacuku** [comment]
We can already merge it.

**Review by jasondellaluce — APPROVED** [review]
/approve

**Pull request merged**
