### PR TITLE
Fix link to events generator project

### PR DESCRIPTION
**Pull request by tspearconquest**
**What type of PR is this?**

> Uncomment one (or more) `/kind <>` lines:

> /kind bug

> /kind cleanup

> /kind design

> /kind user-interface

> /kind content

> /kind translation

**Any specific area of the project related to this PR?**

> Uncomment one (or more) `/area <>` lines:

> /area blog

> /area documentation

> /area videos

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:

Fixes #

**Special notes for your reviewer**:

### CODE REVIEW

**Comment by tspearconquest** [comment]
I tried to follow the link to the Contributing guide to get the DCO signoff, but that link is broken as well.

How do I get a broken link fixed when your link to guide me on how to get DCO signoff is also broken?

**Comment by leogr** [comment]
> Hello, I tried to follow the link to the Contributing guide to get the DCO signoff, but that link is broken as well.
> 
> How do I get a broken link fixed when your link to guide me on how to get DCO signoff is also broken?

First of all, thank you for catching this and for your contribution :) 

You're right, the link is broken, unfortunately. Sorry for the inconvenience. 
The correct one is https://github.com/falcosecurity/.github/blob/master/CONTRIBUTING.md#developer-certificate-of-origin

Anyway, you can easily fix the issue by running the following commands from your local branch:
```
git commit --amend -s
git push --force-with-lease
```

Feel free to contact me if you need any further support!

Thanks, again.

**Comment by tspearconquest** [comment]
Hi Leo,

I actually used the Github UI to make this edit without leaving the website, and so I never cloned the repo to be able to run git from the command line, so I assume there are some extra steps I'll need to take in order to get on the right branch or tag. Can you let me know what those missing steps are in the sequence below?

```
git clone
missing steps
git commit --amend -s
git push --force-with-lease
```

**Comment by leogr** [comment]
> Hi Leo,
> 
> I actually used the Github UI to make this edit without leaving the website, and so I never cloned the repo to be able to run git from the command line, so I assume there are some extra steps I'll need to take in order to get on the right branch or tag. Can you let me know what those missing steps are in the sequence below?
> 
> ```
> git clone
> missing steps
> git commit --amend -s
> git push --force-with-lease
> ```

Here is it:
```shell
git clone https://github.com/tspearconquest/falco-website.git
cd falco-website
git checkout --track origin/patch-1
git commit --amend -s
git push --force-with-lease
```
N.B.:
Assuming you already configured [your identity](https://git-scm.com/book/en/v2/Getting-Started-First-Time-Git-Setup#_your_identity) in git and your git is authenticated with GitHub (follow their official docs in case of doubt).

**Comment by tspearconquest** [comment]
Thank you, I have followed it to completion.

**Review by fntlnz — APPROVED** [review]

**Pull request merged**
