### PR TITLE
Translated rules documents to Japanese 200402

### PR DESCRIPTION
**Pull request by TakaoShimizu**
Signed-off-by: TakaoShimizu <takao.shimizu@sysdig.com>

What type of PR is this?
/kind content
/kind transalation
/area documentation
What this PR does / why we need it:

Useful for Japanese
Special notes for your reviewer:

/assign @leodido
/assign @fntlnz

### CODE REVIEW

**Comment by leodido** [comment]
Some modifications to the template (e.g., shortcode for config.yaml) need to be done in order to account for different languages while interpolating data.

Probably also some other modifications, too. Thus, for now

/hold

**Comment by TakaoShimizu** [comment]
Hi, leodido

Thanks for review and update. 
I will translate data/en/config.yaml and jp/docs/alerts/_index.md!

**Comment by TakaoShimizu** [comment]
I translated data/en/config.yaml and jp/docs/alerts/_index.md and so on!

**Comment by TakaoShimizu** [comment]
Translated all of Falco documentation to Japanese :-)

**Pull request merged**
